version: "3.8"

services:
  redis:
    image: redis:7
    container_name: probo-redis
    ports:
      - "6379:6379"
      
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: probo-server
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=probo-redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://probo-redis:6379
