version: "3.8"

services:
  redis:
    image: redis:7
    container_name: probo-redis
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: probo-server
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=probo-redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://probo-redis:6379
      - DATABASE_URL=postgresql://probo:probo123@probo-postgres:5432/probodb
      
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: probo-web
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - REDIS_URL=redis://probo-redis:6379
      - DATABASE_URL=postgresql://probo:probo123@probo-postgres:5432/probodb

  order-queue:
    build:
      context: .
      dockerfile: packages/order-queue/Dockerfile
    container_name: probo-order-queue
    depends_on:
      - redis
    environment:
      - REDIS_HOST=probo-redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://probo-redis:6379

  archiver:
    build:
      context: .
      dockerfile: services/archiver/Dockerfile
    container_name: probo-archiver
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=probo-redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://probo-redis:6379
      - DATABASE_URL=postgresql://probo:probo123@probo-postgres:5432/probodb

  wss:
    build:
      context: .
      dockerfile: services/wss/Dockerfile
    container_name: probo-wss
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=probo-redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://probo-redis:6379

  postgres:
    image: postgres:15
    container_name: probo-postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=probo
      - POSTGRES_PASSWORD=probo123
      - POSTGRES_DB=probodb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
