import type { Metadata } from "next";
import "./globals.css";
import SessionWrapper from "./sessionWrapper";

export const metadata: Metadata = {
  title: "Probably",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
